fix icmpv6_solicit.c:161:30: error: 'struct net_driver_s' has no member named 'd_mac'
by make d_mac field always exist since not all ipv6 net driver have mac address(e.g. SLIP).

Change-Id: I7665bc28e6c31e3be392fa1194c1b188df2fb110
Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>