fix build error after merge
1.error: 'NVIC_SYSH_PRIORITY_STEP' undefined
2.unresolved conflict in libs/libc/misc/Make.defs

Change-Id: Ie02eaabfbc1fb3bc2f1aa0f69c20a0f1e752308f
Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>