nuttx/libc: regression in the previous submitted
nuttx/libc/misc/lib_newlib.c: In function '__errno':
nuttx/libc/misc/lib_newlib.c:77:10: warning: implicit declaration of function 'get_errno_ptr' [-Wimplicit-function-declaration]
   return get_errno_ptr();
             ^~~~~~~~~~~~~
nuttx/libc/misc/lib_newlib.c:77:10: warning: return makes pointer from integer without a cast [-Wint-conversion]
   return get_errno_ptr();
             ^~~~~~~~~~~~~~~

Change-Id: I29023d17cb6cb9220e915b6ca7102122e55141e4
Signed-off-by: anchao <anchao@pinecone.net>